[package]
name = "netlify-ddns"
version = "0.2.0"
authors = ["Luke Hsiao <lwhsiao@stanford.edu>"]
edition = "2018"
description = "A simple CLI tool for setting Netlify DNS records."
repository = "https://github.com/lukehsiao/netlify-ddns-rs"
readme = "README.md"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.6"
futures = "0.3.1"
log = "0.4.8"
mockito = "0.21.0"
pretty_env_logger = "0.3.1"
reqwest = "0.9.22"
serde = "1.0.102"
serde_json = "1.0.41"
structopt = "0.3.3"

[profile.release]
debug = false
