[package]
name = "netlify-ddns"
version = "0.1.1"
authors = ["Luke Hsiao <lwhsiao@stanford.edu>"]
edition = "2018"
description = "A simple CLI tool for setting Netlify DNS records."
repository = "https://github.com/lukehsiao/netlify-ddns-rs"
readme = "README.md"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
reqwest = "0.9.20"
failure = "0.1.5"
mockito = "0.20.0"
serde = "1.0.99"
serde_json = "1.0.40"

[profile.release]
lto = true
debug = false
